version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Flutter...
      - git clone https://github.com/flutter/flutter.git -b stable
      - export PATH="$PATH:`pwd`/flutter/bin"
      
  pre_build:
    commands:
      - echo Resolving dependencies...
      - flutter pub get
      # Create key.properties if needed, or rely on env vars in build.gradle
      # Decoding keystore from env var (base64 encoded) if provided
      - |
        if [ -n "$ANDROID_KEYSTORE_BASE64" ]; then
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/app/upload-keystore.jks
        fi

  build:
    commands:
      - echo Building Android App Bundle...
      - flutter build appbundle --release --build-name=1.0.$CODEBUILD_BUILD_NUMBER --build-number=$CODEBUILD_BUILD_NUMBER

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/app/outputs/bundle/release/app-release.aab
  name: android-app-bundle
